import Head from 'next/head'
import Link from 'next/link';

export default function Example() {
  return (
      <div className="flex min-h-screen flex-col items-center justify-center py-2">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
          <Link className="text-blue-600" href="/">
            Back to the home
          </Link>
        </main>
      </div>
  )
}
