import Head from 'next/head'
import Image from 'next/image'
import Navigator from '../src/components/Navigator'
import InfoCard from '../src/components/InfoCard'

export default function Home() {
  return (
    <>
      <Navigator />
      <div className="flex min-h-screen flex-col items-center justify-center py-2">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <InfoCard />
        <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
          <h1 className="text-6xl font-bold">
            Welcome to{' '}
            <a className="text-blue-600" href="https://nextjs.org">
              Next.js!
            </a>
            <div className="rounded-md shadow">
              <a href="#" className="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-base font-medium text-white hover:bg-indigo-700 md:py-4 md:px-10 md:text-lg">Get started</a>
            </div>
          </h1>
        </main>
      </div>
    </>
  )
}
